<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DEV_DEL_DEEPAK" ignored="0" name="Default test" tests="2" failures="2" timestamp="04 Feb 2020 15:08:42 GMT" time="25.031" errors="0">
  <testcase name="testMethodA" time="0.0" classname="com.DataproviderITestContext.ParameterByMethodInDataprovider">
    <failure type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] com.DataproviderITestContext.dataproviderByMethod.getdDataProvider(net.bytebuddy.jar.asm.commons.Method) parameters unresolved:  at 0 type class net.bytebuddy.jar.asm.commons.Method
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] com.DataproviderITestContext.dataproviderByMethod.getdDataProvider(net.bytebuddy.jar.asm.commons.Method) parameters unresolved:  at 0 type class net.bytebuddy.jar.asm.commons.Method

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:176)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:114)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testMethodA -->
  <testcase name="testMethodB" time="0.0" classname="com.DataproviderITestContext.ParameterByMethodInDataprovider">
    <failure type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] com.DataproviderITestContext.dataproviderByMethod.getdDataProvider(net.bytebuddy.jar.asm.commons.Method) parameters unresolved:  at 0 type class net.bytebuddy.jar.asm.commons.Method
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] com.DataproviderITestContext.dataproviderByMethod.getdDataProvider(net.bytebuddy.jar.asm.commons.Method) parameters unresolved:  at 0 type class net.bytebuddy.jar.asm.commons.Method

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:176)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:114)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testMethodB -->
</testsuite> <!-- Default test -->
